# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: nixpkgs-fmt
        name: nixpkgs-fmt
        description: Format nix code with nixpkgs-fmt
        entry: nixpkgs-fmt
        language: system
        files: \.nix$

    -   id: statix
        name: statix
        description: Lint Nix code with statix
        entry: statix check
        language: system
        files: \.nix$

    -   id: deadnix
        name: deadnix
        description: Find dead Nix code
        entry: deadnix
        language: system
        files: \.nix$

    -   id: nil
        name: nil
        description: Check Nix code with nil
        entry: nil diagnostics
        language: system
        files: \.nix$

    -   id: flake-check
        name: flake-check
        description: Check if flake.nix is valid
        entry: nix flake check
        language: system
        pass_filenames: false
        files: flake\.nix$ 