default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]

  # Replace the Alejandra remote hook with a local one
  - repo: local
    hooks:
      - id: alejandra
        name: Format Nix files with Alejandra
        entry: alejandra
        language: system
        files: '.*\.nix$'
        exclude: 'vendor/.*'
        stages: [pre-commit]

      - id: check-flake
        name: Check Nix Flake
        entry: nix flake check
        language: system
        pass_filenames: false
        files: '(flake\.nix|.*\.nix)$'
        stages: [pre-commit]

      - id: statix
        name: Static analysis for Nix
        entry: statix check
        language: system
        pass_filenames: false
        files: '.*\.nix$'
        stages: [pre-commit]

      - id: deadnix
        name: Find dead Nix code
        entry: deadnix
        language: system
        pass_filenames: false
        files: '.*\.nix$'
        stages: [pre-commit]
