default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: alejandra
        name: Format Nix files with Alejandra
        entry: alejandra
        language: system
        files: \.nix$

      - id: check-flake
        name: Check Nix Flake
        entry: nix flake check
        language: system
        pass_filenames: false
        files: \.nix$

      - id: statix
        name: Static analysis for Nix
        entry: statix check
        language: system
        pass_filenames: false
        files: \.nix$

      - id: deadnix
        name: Find dead Nix code
        entry: deadnix
        language: system
        pass_filenames: false
        files: \.nix$
